#!/usr/bin/env bash
# A script to redirect /redirect_me to another page

# Updating packages and installing nginX
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to github
redirecting_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Yator1 permanent;"
sudo sed -i "s/server_name _;/$redirecting_string/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
