#!/usr/bin/env bash
# A script to redirect /redirect_me to another page

# Updating packages and installing nginX
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to github
location_path="/redirect_me"
redirection_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Combine location path and redirection URL
rewrite_config="rewrite ^$location_path\$ $redirection_url permanent;"

# Insert the redirection configuration into the Nginx configuration file
sudo sed -i "/server_name _;/a \\\t$rewrite_config" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
