#!/usr/bin/env bash
# A script to redirect /redirect_me to another page

# Updating packages and installing nginX
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to a youtube video
redirect_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Insert the redirection configuration into the Nginx configuration file
sudo sed -i '/server_name _;/a \	rewrite ^/redirect_me $redirect_url permanent;' /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart
