#!/usr/bin/env bash
# A script to redirect /redirect_me to another page

# Updating packages and installing nginX
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Setting up /redirect_me to a youtube video
location_path="/redirect_me"
redirection_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Insert the redirection configuration into the Nginx configuration file
sudo sed -i "/server_name _;/a \\
	location $location_path { \\
	\trewrite ^ $redirection_url permanent; \\
	}\n" /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\
	listen 80 default_server;\n\
	\terror_page 404 \/404.html;\n\
	\tlocation = \/404.html {\n\
	\t\troot \/var\/www\/html;\n\
	\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
