#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# update the package list 
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy 2.0
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy


# HAProxy configuration
server_config=\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend haproxy_frontend
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 111844-web-01 18.210.14.120:80 check
    server 111844-web-02 54.90.8.146:80 check
"

#Overwrite the existing configurations
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
