#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

ip_add=$1
if [ -z "$ip_add" ]; then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$ip_add"
fi
