#!/usr/bin/env bash
#This is a script that displays pid as well as process name and
#those that start with bash

process_list=$(pgrep -f bash)

for pid in $process_list; do
	p_name=$(ps -p "$pid" -o comm=)
	echo "$pid $p_name"
done
