#!/usr/bin/env bash
#This script displays numbes from 1 to 100
# displays 'FizzBuzz' when number is multiple of 3 and 5
# displays 'Fizz' when number is multiple of 3
# displays 'Buzz' when number is a multiple of 5
# otherwise display the number

i=1

while ((i <= 100)); do
	if (( i%3 == 0 && i%5 ==0)); then
		echo "FizzBuzz"
	elif (( i%3 == 0)); then
		echo "Fizz"
	elif (( i%5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	
	((i++))
done
