#!/usr/bin/env bash
#This script prints best school 8 times then hi then best school

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
