#!/usr/bin/env bash
#This script displays the content of the current directory in list format

for file in *; do
	if [[ -f "$file" && ! "$file" == .* ]]; then
		name="${file#*-}"
		echo "$name"
	fi
done
