#!/usr/bin/env bash
# A Bash script that configures an ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new

# localhost mapping
sed -i 's/^127.0.0.1.*$/127.0.0.1 localhost\n127.0.0.2 localhost/' ~/hosts.new

# Facebook.com mapping
sed -i '/facebook.com/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original hosts file
cp -f ~/hosts.new /etc/hosts
