#!/usr/bin/env bash
# A script to run container as the nginx user.

# Set read-only permissions for the Nginx configuration file
sudo chmod 400 /etc/nginx/nginx.conf
# Change ownership of the Nginx configuration file to user and group 'nginx'
sudo chown nginx:nginx /etc/nginx/nginx.conf
# Modify the Nginx site configuration to use port 8080 instead of 80
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Terminate any running Apache processes
pkill apache
# Restart nginx
sudo -u nginx service nginx restart
